<?php
return [
	/**
	 * The view to use when rendering the full HTML page
	 * for the initial response to the browser.
	 */
	'html_template' => 'inertia::default',

	/**
	 * The name of the view variable that stores the content security
	 * policy nonce. It's assigned to the view by the ContentSecurityPolicy
	 * middleware, and is used to whitelist the tags generated by php-vite
	 * under a nonce-based CSP. Set this to false to disable the behavior.
	 */
	'csp_nonce_var' => '_csp_nonce_',
];