<?php
return [
	/**
	 * The path to the manifest file generated by Vite.
	 * Only needed if you change the default path in Vite,
	 * otherwise the key should be omitted entirely.
	 */
	//'manifest' => null,

	/**
	 * The path to the hot module replacement file generated
	 * by Vite. Only needed if you change the default path in
	 * Vite, otherwise the key should be omitted entirely.
	 */
	//'hot_file' => null,

	/**
	 * The base path for the Vite assets. Should match the
	 * `base` option in your Vite configuration, but could
	 * also point to a CDN or other asset server, if you are
	 * serving assets from a different domain.
	 */
	'base_path' => '/',
];