<?php
namespace inventor96\Inertia;

use mako\application\Application;
use mako\config\Config;
use mako\file\FileSystem;
use mako\http\Request;
use mako\http\Response;
use mako\view\renderers\RendererInterface;
use mako\view\ViewFactory;
use mindplay\vite\Manifest;
use mindplay\vite\Tags;

class InertiaRenderer implements RendererInterface {
	protected string $hot_file;

	public function __construct(
		protected Request $request,
		protected Response $response,
		protected Config $config,
		protected ViewFactory $view_factory,
		protected FileSystem $file_system,
		protected Application $app,
		protected Inertia $inertia,
	) {}

	public function render(string $view, array $data = []): string {
		// build the page object
		$page = $this->getInertiaObject($view, $data);

		// render json response if the request is an inertia request
		if ($this->request->isAjax() && $this->request->headers->get('X-Inertia')) {
			$this->response->headers->add('X-Inertia', 'true');
			$this->response->setType('application/json');
			return $page;
		}

		// build vite stuff for a full page render
		$vite_manifest = $this->getViteManifest();

		// render the full page
		$this->response->setType('text/html');
		return $this->view_factory->render(
			$this->config->get('inertia::inertia.html_template', 'inertia::default'),
			[
				'page' => $page,
				'tags' => $this->applyNonce(
					$vite_manifest->createTags('app/resources/js/app.js'),
					$data['_csp_nonce_'] ?? null,
				),
			]
		);
	}

	/**
	 * Applies a content security policy nonce to the tags generated by
	 * php-vite. The nonce must match the one used in the Content-Security-Policy
	 * response header, i.e. the one assigned to the `_csp_nonce_` view variable
	 * by Mako's ContentSecurityPolicy middleware. When no nonce is set, the tags
	 * are returned unchanged.
	 *
	 * @param Tags $tags The tags generated by php-vite.
	 * @param string|null $nonce The content security policy nonce.
	 * @return Tags
	 */
	protected function applyNonce(Tags $tags, ?string $nonce): Tags {
		if ($nonce === null || $nonce === '') {
			return $tags;
		}

		$attribute = 'nonce="' . htmlspecialchars($nonce, ENT_QUOTES, 'UTF-8') . '"';

		return new Tags(
			preload: str_replace('<link', "<link {$attribute}", $tags->preload),
			css: str_replace('<link', "<link {$attribute}", $tags->css),
			js: str_replace('<script', "<script {$attribute}", $tags->js),
		);
	}

	protected function getInertiaObject(string $view, array $data): string {
		// the view factory merges its own globals into the view data, so
		// remove them from the page props before sending them to the client
		$data = array_diff_key($data, ['__charset__' => true, '__viewfactory__' => true, '_csp_nonce_' => true]);

		$q = http_build_query($this->request->getQuery()->all());
		return json_encode([
			'component' => $this->getVueView($view),
			'props' => $data,
			'sharedProps' => $this->inertia->getShareKeys(),
			'url' => $this->request->getPath() . ($q ? '?' . $q : ''),
			'version' => $this->inertia->getVersion(),
		], JSON_THROW_ON_ERROR);
	}

	protected function getVueView(string $view): string {
		return str_replace([
			(function() { /** @var ViewFactory $this */ return $this->path; })->call($this->view_factory) . DIRECTORY_SEPARATOR, // remove the view factory's base path
			'Pages/', // remove the pages folder - unix
			'Pages\\', // remove the pages folder - windows
			'.vue', // remove the file extension
		], '', $view);
	}

	protected function getViteManifest(): Manifest {
		$hot = $this->isHot();
		$force_base = $this->config->get('inertia::vite.force_base_path', false);

		return new Manifest(
			$hot,
			$this->config->get('inertia::vite.manifest', $this->app->getPath() . '/../public/manifest.json'),
			$hot && !$force_base
				? $this->file_system->get($this->getHotFile()) . '/'
				: $this->config->get('inertia::vite.base_path', '/'),
		);
	}

	protected function isHot(): bool {
		return $this->file_system->isFile($this->getHotFile());
	}

	protected function getHotFile(): string {
		// populate the hot file path if it's not already populated
		if (!isset($this->hot_file)) {
			$this->hot_file = $this->config->get('inertia::vite.hot_file')
				?? $this->app->getPath() . '/../public/hot';
		}

		return $this->hot_file;
	}
}